CREATE DATABASE todo;

USE todo;

CREATE TABLE lists (

    id VARCHAR(36) PRIMARY KEY,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);

CREATE TABLE tasks (

    id INT AUTO_INCREMENT PRIMARY KEY,

    list_id VARCHAR(36) NOT NULL,

    title VARCHAR(255) NOT NULL,

    done BOOLEAN DEFAULT FALSE,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    FOREIGN KEY(list_id)

        REFERENCES lists(id)

        ON DELETE CASCADE

);
